apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-rental
  template:
    metadata:
      labels:
        app: car-rental
    spec:
      containers:
        - name: car-rental
          image: ghcr.io/rashraj/car-rental:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: car-rental
