### car-rental-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrental-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrental
  template:
    metadata:
      labels:
        app: carrental
    spec:
      containers:
      - name: car-rental-app
        image: ghcr.io/rashraj/car-rental-app

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
  namespace: argocd

spec:
  selector:
    app: car-rental
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

##### END OF car-rental-app.yaml
